services:
  investigation-container:
    build: .
    container_name: investigation-tool
    # Security: Run as non-root user
    user: "1000:1000"
    # Enable GUI applications
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      # X11 socket for GUI support
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Mount Downloads folder as read-only for investigation
      - ${HOME}/phishing/Downloads:/home/investigator/downloads:ro
      # Optional: Mount for investigation results (read-write)
      - ./investigations:/home/investigator/investigations:rw
    # Network mode for web browsing
    network_mode: bridge
    # Keep container running
    stdin_open: true
    tty: true
    # Security options
    security_opt:
      - no-new-privileges:true
    # Limit capabilities (drop all, add only necessary ones)
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    # Resource limits
    mem_limit: 2g
    cpus: 2.0