services:
  investigation-container:
    build: .
    container_name: investigation-tool
    # Security: Run as non-root user
    user: "0:0"  # Need root for RDP service, but will switch to investigator user
    # Environment for RDP
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      # Mount Downloads folder as read-only for investigation
      - ${HOME}/phishing/Downloads:/home/investigator/downloads:ro
      # Optional: Mount for investigation results (read-write)
      - ./investigations:/home/investigator/investigations:rw
    # Network mode for web browsing and RDP access
    network_mode: bridge
    # Expose RDP port
    ports:
      - "3389:3389"
    # Keep container running
    stdin_open: true
    tty: true
    # Security options (relaxed for RDP service)
    security_opt:
      - no-new-privileges:false
    # Resource limits
    mem_limit: 4g
    cpus: 2.0